name       : ccnet
version    : 6.1.8
release    : 9
source     :
    - https://github.com/haiwen/ccnet/archive/v6.1.8.tar.gz : b55636bf95232dc1db70d3604d0bebb7c3d730292d15b9b6c5b951307eb69762
license    : GPL-2.0-only
component  : programming
summary    : Ccnet is a framework for writing networked applications in C.
description: |
    Ccnet is a framework for writing networked applications in C.
builddeps  :
    - pkgconfig(libevent)
    - pkgconfig(libsearpc)
    - pkgconfig(openssl)
    - pkgconfig(sqlite3)
    - openldap-devel
    - vala
setup      : |
    %autogen \
        --disable-server \
        --disable-server-pkg \
        --disable-static \
        --enable-static-build
build      : |
    %make
install    : |
    %make_install
