name       : ccnet
version    : 6.1.5
release    : 8
source     :
    - https://github.com/haiwen/ccnet/archive/v6.1.5.tar.gz : 763296486f8cc51b439355e87dac8cb71975689024bddb359b0456aa8dbd518f
license    : GPL-2.0
component  : programming
summary    : Ccnet is a framework for writing networked applications in C.
description: |
    Ccnet is a framework for writing networked applications in C.
builddeps  :
    - pkgconfig(libevent)
    - pkgconfig(libsearpc)
    - pkgconfig(openssl)
    - pkgconfig(sqlite3)
    - openldap-devel
    - vala
setup      : |
    %autogen \
        --disable-server \
        --disable-server-pkg \
        --disable-static \
        --enable-static-build
build      : |
    %make
install    : |
    %make_install
