name       : ccnet
version    : 6.1.6
release    : 7
source     :
    - https://github.com/haiwen/ccnet/archive/v6.1.6.tar.gz : c6ecec39b21dc92489f77b1975d808f6e7898fcbe623e3fb22dd5a39e1a8faf4
license    : GPL-2.0
component  : programming
summary    : Ccnet is a framework for writing networked applications in C.
description: |
    Ccnet is a framework for writing networked applications in C.
builddeps  :
    - pkgconfig(libevent)
    - pkgconfig(libsearpc)
    - pkgconfig(openssl)
    - pkgconfig(sqlite3)
    - openldap-devel
    - vala
setup      : |
    %autogen \
        --disable-server \
        --disable-server-pkg \
        --disable-static \
        --enable-static-build
build      : |
    %make
install    : |
    %make_install
