name       : ccnet
version    : 6.1.3
release    : 5
source     :
    - https://github.com/haiwen/ccnet/archive/v6.1.3.tar.gz : 0ac3dcd86d22f6bb729027783da8ea14f832276982e36cc814fda0cf3ed78050
license    : GPL-2.0
component  : programming
summary    : Ccnet is a framework for writing networked applications in C.
description: |
    Ccnet is a framework for writing networked applications in C.
builddeps  :
    - pkgconfig(libevent)
    - pkgconfig(libsearpc)
    - pkgconfig(openssl)
    - pkgconfig(sqlite3)
    - openldap-devel
    - vala
setup      : |
    %autogen \
        --disable-server \
        --disable-server-pkg \
        --disable-static \
        --enable-static-build
build      : |
    %make
install    : |
    %make_install
